export const cardanoNftCollections = [
  "EarthNode",
  "SpaceBudz",
  "Tavern Squad",
  "Clay Nation",
  "Cornucopias Land Sale - Zones 1-3",
  "DEADPXLZ",
  "Tappy by TapTools",
  "Mekka Dynasty",
  "ADA Handle",
  "Strongholds by House Of Titans",
  "The Mallard Order",
  "Baby Crocs Club",
  "Snekkies",
  "Cornucopias File Node Access Key",
  "Perps",
  "[Deprecated] Budz",
  "BudzStrategy",
  "House Of Titans",
  "Cardano Crocs Club",
  "The Wojaks - Season 2",
  "Money Frogs: Pondora's Pioneers",
  "Tavern Squad - Shrines",
  "The Farm - Hogs",
  "Jellycubes",
  "KWIC - Keyboard Warriors Internet Cafe",
  "Book.io - Gutenberg Bible Collection",
  "Aquafarmers",
  "Chilled Kongs",
  "HOSKY C(ash grab)NFT",
  "Clay Nation x Good Charlotte by Clay Mates",
  "$C4 Player Pass",
  "S#!tty",
  "Toolheads",
  "Diamond Hooves",
  "Boss Cat Rocket Club",
  "OREMOB",
  "The Wojaks PFP Collection",
  "Goofy Gophers Mining Club",
  "T1 ADAM LAUNCH PASS",
  "The Betski Wolfpack",
  "ONE",
  "Salty Seagulls Society",
  "Cornucopias Custom Dome Sale",
  "Risk - The Warthogs Brigade",
  "Stag Alliance",
  "Radioactive Crocs Club",
  "First Knight",
  "Zombie Chains",
  "Ancient Dragon",
  "CTV - EarthVault",
  "Cornucopias Bubblejett Sprinter OG Custom 2022",
  "CardanoBits",
  "Pavia",
  "Dragon Weapons",
  "Walkers",
  "Cornucopias Bubblejett Sprinter 2022",
  "Bizarre Stars",
  "Mandala Sovereigns",
  "Black Flag",
  "BANK- Heroes and Villians",
  "Tappy02 by TapTools",
  "Pitches at Clay Nation",
  "BANK- Bankcard",
  "The Working Dead",
  "Mallard Order Invitation",
  "Cornucopias Valkyrie F9-R 2024",
  "Walkers",
  "Farm Eggs",
  "Extras Clay Mates",
  "Babysneklets",
  "Farmer Joe Bobblehead Holiday",
  "Frigid",
  "Melting Moonboy",
  "Xerberus Node",
  "The Wojaks - Holder Card",
  "JRNY CLUB",
  "CardanoProxies",
  "Neo Vikings",
  "Knights of Cornucopias",
  "Baked Nation",
  "Squeaky Squeakers",
  "Ugly Bros",
  "Derp Birds - PRED",
  "ADA PEEPOS",
  "MulgaKongz",
  "Shining pyramids",
  "The Land of Frenchpressley",
  "Beartooth Mountain Saloon",
  "Derp Birds",
  "Bizarre Stars Series 2",
  "TeddyTrooper",
  "Magic Kongs",
  "Shadow Operatives - TCC - Hoarder's Collections",
  "Turtle Syndicate Sidekicks",
  "Cup of Confusion and Intellect",
  "Diamond Hooves Stables",
  "Introverts",
  "Cornucopias Valley Raceworx T3 2023",
  "ARBITER",
  "Neo Vikings ComPASS",
  "GOAT Tribe",
  "CSWAP Origins",
  "Old Money",
  "NFT2Tree",
  "Wise Owls - Main Collection",
  "Over Exposed",
  "Ancient Dragon Relic",
  "Zombie Fight Club Aliens",
  "DRRS: Rabbit Supremes",
  "Nikeverse",
  "Filter and Sort",
  "Mandala Sovereigns",
  "NFT2Tree Douglas Fir CM",
  "Infinity Rising Marksman Rifles",
  "Cornucopias Shotguns",
  "Clay Mates",
  "Skullball",
  "The Enlightentmint",
  "Inmates - Females",
  "The Ape Society",
  "Risk - Ultimate OG",
  "EquineNFT Pioneer Horses",
  "Cornucopias GTI Javelin 2022",
  "Inmates Library Pass",
  "Gnomeskies 69 Shades of Rug",
  "BlockOwls",
  "Apeing Riot Club",
  "CornMafia Custom Dome Beta Pool V2",
  "The Vault",
  "Cornucopias Rando's Metalworks Sunset Speeder 2024",
  "ADA Inmates",
  "ADA Inmates",
  "The Turtle Syndicate Villains",
  "Poki Lifetime Pass",
  "Jesus 2",
  "Farm Piglets",
  "BeezHive - Beez Army 1.0",
  "unsigned_algorithms",
  "CardanoCity",
  "DiscoSolaris",
  "Stag Alliance Portal Pass",
  "metaPXLZ",
  "BlockOwls",
  "BMB Miners",
  "SlothWifs",
  "Dead Rabbit Resurrection Society",
  "Elysium Titans",
  "Bizarre Stars Series 1 Promos",
  "Hog Sweeper Pass",
  "Risk - Tank Domination",
  "Panda Society",
  "The Ancestors",
  "CSWAP Allies",
  "Pond - Theta Collection",
  "Meme Miners: Mining Pass",
  "The Capitalist Clowns",
  "Bizarre Budz",
  "HOPS Brewers",
  "FLDT ISPO reward",
  "Funplastic",
  "Frankenstein",
  "NFT2Tree Series Two CM",
  "Cheeky Racer CM",
  "Golden Squeak Ticket",
  "Bizarre Stars",
  "Book.io - Tao Te Ching",
  "BeezHive - Honey Jars",
  "Derp Apes",
  "thiscrazylife",
  "Cornucopias Machine Guns",
  "BeezHive - Beez Army 2.0",
  "OREMOB CASES by ENCASE.ART",
  "Essence Crystals by Necro League",
  "The Gameroom Pass",
  "Book.io - The Twelve Chapters of the Infinite Night",
  "Phas3",
  "MulgaTigerz",
  "GOLDEN Snake Pass",
  "GOLDEN Snake Pass",
  "Hellknights",
  "Book.io - The Critique of Pure Reason",
  "Flux Point Pass",
  "Book.io - Thus Spake Zarathustra",
  "Happy Hoppers Club",
  "Risk - The Four Horsemen",
  "Wise Owls - The Inception",
  "COA",
  "Book.io - Prince of Wolves",
  "Book.io - The Decameron",
  "Walkers-BackPacks",
  "Yummi Universe - Naru",
  "Derp Birds - Outposts",
  "Wild Tangz - Series 2",
  "Book.io - A Tale of the Nine Lands",
  "Ug!",
  "Billionaire Bears Club"
];