export const cardanoNftCollections = [
  "The Ape Society",
  "Clay Nation",
  "SpaceBudz",
  "Pavia",
  "Chilled Kongs",
  "DEADPXLZ",
  "Boss Cat Rocket Club",
  "Boss Cat Rocket Parts",
  "House of Titans",
  "Cardano Crocs Club",
  "Yummi Universe",
  "Cornucopias",
  "Mallard Order",
  "Galactic Geckos",
  "Equine",
  "EarthNode",
  "Book.io",
  "Omen",
  "Block Owls",
  "Ada Anvil",
  "JellyCubes",
  "Mutant NFTs",
  "Stag Alliance",
  "Pendants",
  "Virtua Prime",
  "Goofy Gophers Mining Club",
  "CardanoBits",
  "The Galgos",
  "Unsigned Algorithms",
  "Ape Clan",
  "Cardania",
  "Knitties",
  "SNEK NFT",
  "TAVUTI",
  "CryptoPetz",
  "Cardano Warriors",
  "Rhino Generation",
  "Pixel Links",
  "Dirty Birds Society",
  "Mocossi Planet",
  "RaggieZ",
  "Wolves of Rome",
  "Drunken Dragon",
  "DMT Earth",
  "AADA Ninjas",
  "Tokhun Founders",
  "Mynth",
  "Nemonium",
  "The Hoskinsons",
  "Old Money",
  "CryptoDino",
  "Rektangular Studios",
  "AdaMeds",
  "DessertCatNFT",
  "Steve3p_0",
  "Low Poly Project",
  "Punkster Art",
  "AirportNFT",
  "Cardano Species",
  "BrownNFT",
  "SnowPunkz",
  "ADAPunks",
  "DendroRithms",
  "Alonzo Graduation",
  "Weeblewibs CNFT",
  "hypnocat.io",
  "Havoc Worlds",
  "Masked On Buttons",
  "Canuckz NFTs",
  "PS Max Zaxster",
  "Ada-Monsterz",
  "Cardinos",
  "Bitlands",
  "ADA Shoppers Club",
  "LoveOnChain",
  "Clumsy Ghosts",
  "Derp Birds",
  "Crypto Raggies",
  "AdaQuest",
  "CardanoKidz",
  "Zombie Chains",
  "Famous Fox Federation Cardano",
  "Lazy Llamas",
  "Cardano Village",
  "The Dead Rabbits Society",
  "Cardano Thor",
  "Apez Nation",
  "Planet Palz",
  "CNFT Con",
  "The Mad Axeman",
  "Strange Clan",
  "Mycelial Gallery",
  "Unbounded Earth",
  "Mocossi Forest",
  "Ada Realm",
  "Cardano Trees",
  "Hosky NFTs",
  "Tappy World",
  "BCRC Racing",
  "Pavia Land Parcels",
  "Cornucopias Land",
  "Virtua Islands",
  "Cardania Land",
  "Ape Society Cabin Club",
  "Clay Mates",
  "Clay Nation Good Charlotte",
  "The Ape Society Founders",
  "Chilled Kongs Origins",
  "Boss Planet",
  "GhostChain",
  "Ape Society Comics",
  "Angels on Cardano",
  "Knives by Cardano",
  "Ada Invaders",
  "PitchPeas",
  "Crypto Heroez",
  "Cardano City",
  "Freak Club",
  "Project Newm Pass",
  "Abyssine Society",
  "The Goat Tribe",
  "CyberVerse",
  "Raccoon Syndicate",
  "Cardano Bunnies",
  "Pixel Tiles",
  "MetaMates",
  "Ape Society Districts",
  "Bisonic",
  "Pixel Cat Club",
  "PengEggs",
  "The Seal Society",
  "Lil Sappys",
  "Dino League",
  "Ape Society Relics",
  "HoneyBuds",
  "SeaMonkeYS",
  "Cardano Voxel Club",
  "DripDropz Pass",
  "Cardano Aliens",
  "The Adalotls",
  "Lucky Neko",
  "Dead Astronaut Crew",
  "Ada Dolls",
  "Ape Society Founders Cabin",
  "Pineapple Punks",
  "Psychedelic Hogs",
  "Koala Intelligence Agency",
  "The Artist Club",
  "PixelBeasts",
  "Cardano Muffins",
  "CryptoSlammerz",
  "Lobster Challenge",
  "Mecha Penguins",
  "ApeX Club",
  "Meta Pigs",
  "RoboFrens",
  "Ape Islands",
  "Penguin Procession",
  "The Minds of 99",
  "Wild Tangz",
  "Cardano Raptors",
  "Ape Society Keys",
  "Sleekies",
  "Meta Dinos",
  "Toon Titans",
  "Ape Society Pass",
  "Cardano Cacti Club",
  "Crypto Raggiez Origins",
  "AdaComets",
  "Mutant Crocs",
  "Voxel X",
  "Pillz Club",
  "Feline Frenz",
  "Cardano Krakens",
  "Magic Kongs",
  "The Plague",
  "RoboBudz",
  "Ape Society Arcade",
  "MetaDamsels",
  "Block Bears",
  "Crypto Hamsters",
  "Ape Society Bots",
  "Budz Club",
  "Pixel Pals",
  "Ada Knights",
  "Chroma Cats",
  "AdaZoo",
  "Dream Dinos",
  "Kong Labs",
  "Cardano Sharks",
  "Ape Society Estates",
  "House of Titans Founders",
  "Cardano Craniums",
  "Pixel Pirates",
  "Ape Society Artifacts",
  "Frosties CNFT",
  "Kidz on Cardano",
  "Ada Frogs",
  "Cardano Phoenixes",
  "MetaMonks",
  "Stellar Hood",
  "Cardano Explorers",
  "Ape Society Avatars",
  "Ancient Kongs",
  "Titan Forge",
  "Cardano Nomads",
  "Pixel Nomads",
  "Ape Society Treasury",
  "Block Party Budz",
  "Cardano Penguins",
  "Celestial Crocs",
  "Neo Titans",
  "CNFT Legends",
  "OnChain Monkeys",
  "Ada Robots",
  "Cardano Drifters",
  "Titan Relics",
  "Space Pugs",
  "CryptoCapys",
  "Cardano Dreamers",
  "Meta Titans",
  "Ape Society Clubhouse",
  "Voxel Titans",
  "Cardano Outlaws",
  "House of Titans Genesis"
];